# Generated by Django 4.2.3 on 2023-10-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_management', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=100)),
                ('expire_date', models.DateField()),
                ('discount_percentage', models.IntegerField(default=0)),
                ('product_offer_slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('product_offer_image', models.ImageField(upload_to='product_offer/images/')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ManyToManyField(to='store.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=100)),
                ('expire_date', models.DateField()),
                ('discount_percentage', models.IntegerField(default=0)),
                ('category_offer_slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('category_offer_image', models.ImageField(upload_to='category_offer/images/')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(to='category_management.category')),
            ],
        ),
    ]
