# Generated by Django 4.2.3 on 2023-10-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
