# Generated by Django 4.2.3 on 2023-09-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_management', '0002_wallettransaction_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
