# Generated by Django 4.2.3 on 2023-08-09 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_management', '0002_rename_slug_category_cat_slug_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
