# Generated by Django 4.2.3 on 2023-08-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_management', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
