# Generated by Django 4.2.3 on 2023-10-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_wallet_used',
            field=models.BooleanField(default=False),
        ),
    ]
