# Generated by Django 4.2.3 on 2023-09-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order placed', 'Order placed'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Cancelled by Admin', 'Cancelled by Admin'), ('Cancelled by User', 'Cancelled by User'), ('Returned', 'Returned')], default='New', max_length=20),
        ),
    ]
