# Generated by Django 4.2.3 on 2023-09-18 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_management', '0001_initial'),
        ('orders', '0011_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_discount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon_management.coupon'),
        ),
    ]
